---
# tasks file for assignment-role
---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure Docker is installed (Amazon Linux 2 or RHEL-based)
  yum:
    name: docker
    state: present
  when: ansible_os_family == "RedHat"

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

# Pulling docker image
- name: Pull the application Docker image from Docker Hub
  docker_image:
    name: "{{ docker_image_name }}"
    source: pull
    tag: "{{ docker_image_tag }}"
    force_pull: yes
  register: docker_image_pull

- name: Run the application container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    state: started
    restart_policy: always
    published_ports:
      - "5000:80"  # Exposing port 80 for web application
    env:
      APP_ENV: "production"
    volumes:
      - "{{ app_data_dir }}:/app/data"